# -*- coding: utf-8 -*-
"""streamlit

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hNScsJfD50i0AOy_OPTVep8vq6aeRsah
"""

import streamlit as st
def largest(num1,num2,num3):
  return max(num1,num2,num3)
def main():
  st.title("Find The Largest Number Amoung Given Choices")
  num1=st.number_input("Enter The Number 1")
  num2=st.number_input("Enter the Number 2 ")
  num3=st.number_input("Enter the number 3")
  if st.button("find"):
    large=largest(num1,num2,num3)
    st.write(f"The Largest Number is {large}")
main()

